name: PUBLISH

on:
  push:
    tags:
      - v*

jobs:


  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements-package.txt

      - name: Build
        run: |
          python3 setup.py sdist bdist_wheel

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m twine upload -u __token__ -p $PYPI_TOKEN dist/*
